### ISSUE TITLE
What exact version (and options) of Potree Converter is needed

### ISSUE THREAD

**Issue by frontw** [fkie/potree_rviz_plugin#1]
Hi! Thanks for the project. 

I trying to convert my .las cloud to load it into this RViz plugin. But for the current version of converter, it says, that the 2.0 format is not supported. And for 1.7 version of the converter, I have "Type is not convertible to string" msg.

**Comment by roehling** [comment]
I originally wrote the plugin for PotreeConverter 1.6. I've seen the same error today, looks like the metadata format has changed. Regarding options, I never used any special options, i.e. `./PotreeConverter -i pointcloud.las -o potree-folder` should work.

I plan to add additional support for the new 1.8 format (for some reason, the format version in the Potree files is off-by-one) and the 2.0 format, but I don't have the time right now.

**Comment by roehling** [comment]
I know it has been a while, but I just committed code to support all Potree versions from 1.6 up to the latest 2.1.1 (without compression though)
